title: Decentralized Identity and Access Management
description: An open-source and decentralied Identity and Access Management protocol
google_analytics: UA-70853715-2

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman