title: Blockchain Identity and Access Management
description: An Open-Source & Decentralized Identity and Access Management Protocol
google_analytics: G-99W738Y5WW

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman
