title: Blockchain Identity and Access Management
description: An Open-Source & Decentralized Identity and Access Management Protocol
google_analytics: UA-70853715-2

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman
